# Generated by Django 2.0.3 on 2018-03-22 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBankDetails',
            fields=[
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('s_accno', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='SellerBusinessDetails',
            fields=[
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credit_card_no', models.TextField(max_length=16)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sname', models.CharField(max_length=30)),
                ('semail', models.EmailField(max_length=254)),
                ('sphone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('scompany_name', models.CharField(max_length=100)),
            ],
        ),
    ]
