# Generated by Django 2.0.3 on 2018-03-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T',
            fields=[
                ('no', models.IntegerField(primary_key='true', serialize=False)),
            ],
        ),
    ]
