# Generated by Django 2.0.3 on 2018-03-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
