# Generated by Django 2.0.3 on 2018-03-19 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_t_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBusinessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_no', models.TextField(max_length=16)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('sid', models.TextField(primary_key=True, serialize=False)),
                ('sname', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sellerbusinessdetails',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app1.SellerDetails'),
        ),
    ]
