# Generated by Django 2.0.3 on 2018-03-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180319_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdetails',
            name='sid',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='sname',
            field=models.CharField(max_length=30),
        ),
    ]
