# Generated by Django 2.0.3 on 2018-04-02 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180402_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerbusinessdetails',
            name='gst_flag',
            field=models.CharField(choices=[('empty', 'empty'), ('inprocess', 'inprocess'), ('validated', 'validated'), ('not validated', 'not validated')], default='empty', max_length=15),
        ),
        migrations.AlterField(
            model_name='sellerbusinessdetails',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid GST Number', regex='^([0][1-9]|[1-2][0-9]|[3][0-5])([a-zA-Z]{5}[0-9]{4}[a-zA-Z]{1}[1-9a-zA-Z]{1}[zZ]{1}[0-9a-zA-Z]{1})+$')]),
        ),
    ]
