# Generated by Django 2.0.3 on 2018-04-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20180402_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdetails',
            name='sKYC',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='sKYC_flag',
            field=models.CharField(choices=[('empty', 'empty'), ('inprocess', 'inprocess'), ('validated', 'validated'), ('not validated', 'not validated')], default='empty', max_length=15),
        ),
    ]
