# Generated by Django 2.0.3 on 2018-04-19 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('app1', '0006_auto_20180411_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitValueDetails',
            fields=[
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('overall_value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('overall_value_health', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('late_shipment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('on_time_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('hit_to_success_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('late_shipment_recommendations', models.TextField(default='ABC')),
                ('positive_feedbacks', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('negative_feedbacks', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('gst_value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('kyc_value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('credit_card_value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'managed': True,
                'db_table': 'traits_value_details',
            },
        ),
        migrations.AlterField(
            model_name='sellerbusinessdetails',
            name='gst_flag',
            field=models.CharField(choices=[('empty', 'empty'), ('inprocess', 'inprocess'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='empty', max_length=15),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='sKYC_flag',
            field=models.CharField(choices=[('empty', 'empty'), ('inprocess', 'inprocess'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='empty', max_length=15),
        ),
    ]
