# Generated by Django 2.0.3 on 2018-06-06 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Buyer',
            },
        ),
        migrations.CreateModel(
            name='BuyerDetails',
            fields=[
                ('bid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'buyer_details',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cname', models.TextField(max_length=30)),
                ('subCategory', models.TextField(max_length=30)),
                ('subCategoryCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hit_date', models.DateField()),
                ('hits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('oid', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('OD', 'ontime_delivery'), ('LD', 'late_delivery'), ('C', 'cancelled'), ('R', 'returned'), ('IP', 'in_process'), ('D', 'dispatched')], default='IP', max_length=2)),
                ('order_date', models.DateField()),
                ('exp_shipment', models.DateField()),
                ('exp_delivery', models.DateField()),
                ('actual_shipment', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.BuyerDetails')),
            ],
            options={
                'managed': True,
                'db_table': 'order_details',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oid', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('OD', 'ontime_delivery'), ('LD', 'late_delivery'), ('C', 'cancelled'), ('R', 'returned')], max_length=2)),
                ('order_date', models.DateField()),
                ('exp_shipment', models.DateField()),
                ('exp_delivery', models.DateField()),
                ('actual_shipment', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Buyer')),
            ],
            options={
                'managed': True,
                'db_table': 'details_of_orders',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('pid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=25)),
                ('no_of_hits', models.IntegerField(default=0)),
            ],
            options={
                'managed': True,
                'db_table': 'product_details',
            },
        ),
        migrations.CreateModel(
            name='ProductMain',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('prod_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('launch_date', models.DateField()),
                ('score', models.IntegerField()),
                ('inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.TextField(max_length=50)),
                ('product_sale_count', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
                ('launch_date', models.DateField()),
                ('score', models.IntegerField()),
                ('inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=25)),
            ],
            options={
                'managed': True,
                'db_table': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('sid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=25)),
            ],
            options={
                'managed': True,
                'db_table': 'seller_details',
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subcategory_name', models.TextField(max_length=30)),
                ('subcategory_sale_count', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='TraitValueDetails',
            fields=[
                ('tid', models.TextField(primary_key=True, serialize=False)),
                ('overall_perf_val', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('late_shipment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('recommendations_lateShipmentRate', models.TextField(max_length=100)),
                ('on_time_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('recommendations_onTimeDeliery', models.TextField(max_length=100)),
                ('hit_to_success_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('recommendations_HitToSucessRatio', models.TextField(max_length=100)),
                ('return_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('recommendations_returnRate', models.TextField(max_length=100)),
                ('positive_feedbacks', models.TextField(max_length=500)),
                ('recommendations_positive_feedbacks', models.CharField(default='abc', max_length=100)),
                ('negative_feedbacks', models.TextField(max_length=500)),
                ('recommendations_negative_feedbacks', models.CharField(default='abc', max_length=100)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Seller')),
            ],
            options={
                'managed': True,
                'db_table': 'traits_value_details',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Seller'),
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Subcategories'),
        ),
        migrations.AddField(
            model_name='productmain',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerDetails'),
        ),
        migrations.AddField(
            model_name='productmain',
            name='sub_cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerDetails'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Seller'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProductDetails'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerDetails'),
        ),
        migrations.AddField(
            model_name='hits',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Products'),
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('oid', 'product_id', 'seller_id', 'buyer_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together={('oid', 'pid', 'sid', 'bid')},
        ),
    ]
